import Head from "next/head";
import { Container, Button } from "react-bootstrap";
import Forbidden from "../../components/401";
import { useAuth } from "../../context/authContext";
import ALink from "../../components/ALink";
const calc_total_price = (packages) => {
  return packages.reduce((a, b) => {
    return { price: parseInt(a.price) + parseInt(b.price) };
  }).price;
};

export default function Profile() {
  const auth = useAuth();
  if (auth.isAuth === false) {
    return <Forbidden />;
  }
  return (
    <div>
      <Head>
        <title>Profile - {auth.user.full_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-3">
        <Container>
          <h2>Welcome {auth.user.full_name}</h2>
          <hr />
          <div className="d-flex w-100 justify-content-between align-items-center">
            <p>Here Are The Packages You Have Applied For</p>
            <ALink href="/packages">
              <Button className="btn-sm">Apply For More</Button>
            </ALink>
          </div>
          <div>
            {auth.user.Packages && auth.user.Packages.length <= 0 && (
              <p>You Are Not Enrolled In Any Packages</p>
            )}
            {auth.user.Packages && auth.user.Packages.length > 0 && (
              <div className="table-responsive">
                <table className="table table-bordered text-center align-center">
                  <thead>
                    <tr>
                      <th>SN</th>
                      <th>Package Name</th>
                      <th>Package Duration</th>
                      <th>Package Price</th>
                      <th>Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {auth.user.Packages &&
                      auth.user.Packages.map((item, index) => {
                        return (
                          <tr key={`user-package-${index}`}>
                            <td>{index + 1}</td>
                            <td>{item.name}</td>
                            <td>{item.duration}</td>
                            <td>Rs. {item.price}</td>
                            <td>
                              <div className="btn-group gap-2">
                                <ALink href={`/packages/${item.id}`}>
                                  <Button variant="warning" className="btn-sm">
                                    Package Details
                                  </Button>
                                </ALink>
                              </div>
                            </td>
                          </tr>
                        );
                      })}
                    {auth.user.Packages && (
                      <tr>
                        <td colSpan={3}>Grand Total</td>
                        <td>
                          Rs.{" "}
                          {calc_total_price(
                            auth.user.Packages ? auth.user.Packages : []
                          )}
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            )}
          </div>
        </Container>
      </div>
    </div>
  );
}
