import Head from "next/head";
import { useEffect, useState } from "react";
import { Container, Row, Col, Card, Button } from "react-bootstrap";
import ALink from "../../components/ALink";
import { GET_PACKAGES } from "../../utils/queries";

export default function Packages() {
  const [packages, setPackages] = useState({ loading: true, data: [] });
  useEffect(async () => {
    try {
      const pkgs = await GET_PACKAGES();
      if (pkgs.status === "error") throw pkgs;
      setPackages({ loading: false, data: pkgs.detail });
      console.log(pkgs);
    } catch (error) {
      setPackages([]);
      console.error(error);
    }
  }, []);

  return (
    <Container className="py-5">
      <Head>
        <title>Packages </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1 className="p-0 pt-3">Our Packages</h1>
        <h5 className="p-0 pb-4">Enroll in Any of these Online</h5>
        <Row>{packages.loading && <p>Loading...</p>}</Row>
        <Row>
          {packages.data.map((item, index) => {
            return (
              <Col
                key={`package-all-${index}`}
                className="col-lg-4 col-md-6 col-sm-12"
              >
                <Card>
                  <Card.Body>
                    <Card.Img src="/images/packages/1.jpg" />
                    <ALink href={`/packages/${item.id}`}>
                      <Card.Title className="text-primary">
                        {item.name}
                      </Card.Title>
                    </ALink>
                    <hr />
                    <p>
                      <b>Duration: </b> {item.duration}
                      <br />
                      <b>Price: </b> Rs. {item.price} Only
                    </p>
                    <hr />
                    <div class=" d-flex justify-content-end">
                      <ALink href={`/packages/${item.id}`}>
                        <Button>Read More</Button>
                      </ALink>
                    </div>
                  </Card.Body>
                </Card>
              </Col>
            );
          })}
        </Row>
      </div>
    </Container>
  );
}

/**
 * 
 * <Col className="col-lg-4 col-md-6 col-sm-12">
            <Card>
              <Card.Body>
                <Card.Img src="/images/packages/1.jpg" />
                <ALink href="/package/1">
                  <Card.Title className="text-primary">
                    Special Title
                  </Card.Title>
                </ALink>
                <div class=" d-flex justify-content-end">
                  {auth.isAuth === true ? (
                    <Button>Enroll</Button>
                  ) : (
                    <ALink href="/auth/login?redirect=/packages">
                      <Button>Login</Button>
                    </ALink>
                  )}
                </div>
              </Card.Body>
            </Card>
          </Col>
 */
